apiVersion: backstage.io/v1alpha1
kind: System
metadata:
  name: consuldotnet
  description: null
  annotations:
    github.com/project-slug: pats/consuldotnet
  tags:
    - dotnet
    - backend
spec:
  owner: null
